<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="192.168.1.6" failures="1" tests="2" name="Test2" time="60.596" errors="0" timestamp="2023-01-03T12:42:38 EET">
  <testcase classname="Tests.testing" name="test2" time="32.392">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
at Tests.testing.test2(testing.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="Tests.testing" name="test3" time="24.037"/>
  <testcase classname="Tests.testing" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Test2 -->
